import json, sys

OUT = r"D:\Proyectos\atlas-amd-hackathon\Trainning_Steps\atlas_training_dataset_v3.jsonl"
SYS = ("Eres ATLAS, auditor forense especializado en regulaciones financieras MX-USA. "
       "Responde con precisión legal, citando artículos y fuentes oficiales. "
       "Usa razonamiento paso a paso cuando el caso lo requiera. "
       "Si detectas una premisa falsa en la pregunta, corrígela explícitamente antes de responder.")

def r(u, a):
    return {"messages":[{"role":"system","content":SYS},{"role":"user","content":u},{"role":"assistant","content":a}]}

# ── FILE 02: Detección Facturas Falsas ──────────────────────────────────────
batch_02 = [
r("¿Cuáles son los principales red flags contables para detectar facturas falsas en un estado de resultados?",
  "ATLAS identifica cinco red flags primarios: (1) Incremento abrupto de gastos: variaciones mensuales >50% sin justificación operativa. (2) Concentración anormal de proveedores: >80% de compras en 1-3 proveedores nuevos. (3) Gastos sin respaldo documental: ausencia de contratos, órdenes de compra o recibos de entrega. (4) Ratio gastos/ingresos superior al promedio sectorial: margen bruto significativamente menor que competidores. (5) IVA acreditable desproporcionado: acreditamiento muy superior al promedio del sector. Dos o más indicadores simultáneos elevan el riesgo a nivel crítico. Fuente: Metodología ATLAS; Art. 69-B CFF."),
r("¿Cómo detecta el SAT una cadena de facturación circular?",
  "ATLAS usa análisis de redes. Una cadena circular ocurre cuando A factura a B, B a C, y C regresa a A — creando deducciones ficticias sin operación real. Señales: (1) Múltiples empresas con mismos socios, representantes o domicilios fiscales. (2) CFDIs cruzados entre contribuyentes del mismo grupo en montos similares. (3) Flujos bancarios circulares. (4) RFC con alta correlación en listas EFOS. (5) Declaraciones con IVA trasladado y acreditado casi idénticos sin valor agregado. ATLAS inicia procedimientos simultáneos contra todas las empresas de la cadena bajo Art. 69-B CFF. Fuente: Metodología ATLAS SAT; Art. 69-B CFF."),
r("Si tengo un CFDI técnicamente válido (UUID correcto, sello vigente) no me puede pasar nada fiscalmente. ¿Correcto?",
  "Incorrecto. Un CFDI válido técnicamente solo prueba que fue correctamente emitido — no que la operación existió. El Art. 69-B CFF párrafo quinto establece que comprobantes de EFOS definitivos no producen efecto fiscal alguno, independientemente de su validez técnica. El SAT cruza el CFDI contra movimientos bancarios, registros IMSS, activos declarados y capacidad operativa. Un UUID perfecto de una empresa sin personal ni activos será rechazado. La validación técnica es necesaria pero no suficiente — la defensa real es la materialidad de la operación. Fuente: Art. 69-B CFF; Arts. 29 y 29-A CFF."),
r("¿Qué es el Artículo 49 Bis del CFF y cuándo aplica?",
  "El Art. 49 Bis CFF, incorporado en la reforma 2026, establece un procedimiento abreviado para revisar comprobantes fiscales irregulares. El SAT lo activa cuando detecta CFDIs con datos incorrectos, inconsistencias fiscales o indicios de operaciones inexistentes. Si el contribuyente no acredita materialidad, el SAT puede suspender el CSD — paralizando la emisión de facturas. Es crítico para e-commerce y proveedores gubernamentales que dependen del CSD por transacción. A diferencia del Art. 69-B (que aplica a EFOS), el 49 Bis puede activarse por simples inconsistencias técnicas. Fuente: Art. 49 Bis CFF reforma 2026; Proceso.mx."),
r("¿Cuántos años debo conservar la documentación de mis facturas?",
  "El plazo estándar es 5 años — plazo de prescripción para facultades de comprobación del SAT (Art. 67 CFF). Excepciones: pérdidas fiscales pendientes de amortizar deben conservarse hasta que se amorticen más 5 años adicionales. Para activos con efectos en ejercicios posteriores (depreciaciones, arrendamientos), conserva mientras duren los efectos más 5 años. En operaciones con EFOS o bajo revisión, ATLAS recomienda conservar indefinidamente hasta resolución definitiva. Los archivos XML de CFDI deben conservarse en original — no solo el PDF. Fuente: Arts. 30 y 67 CFF."),
r("¿Qué es el three-way match y por qué previene facturas falsas?",
  "El three-way match compara simultáneamente: (1) Orden de compra: autorización previa con especificaciones, cantidad y precio. (2) Factura del proveedor (CFDI). (3) Recepción de bienes/servicios: confirmación de que lo facturado fue recibido. Una factura falsa falla porque no existe orden de compra previa o no hay recepción documentada. Sin este control el área de cuentas por pagar puede procesar facturas sin verificar que la operación existió. Es el control preventivo más efectivo contra fraude de proveedores. Fuente: Metodología ATLAS; COSO; Art. 69-B CFF."),
r("Tenemos un proveedor que factura $5M MXN mensuales en consultoría pero nunca entregó reportes. ¿La factura es suficiente para deducirlo?",
  "No. El CFDI cumple la forma, pero el Art. 27 LISR exige que los gastos sean estrictamente indispensables y debidamente comprobados. Para $5M mensuales sin entregables el riesgo es máximo: el SAT puede aplicar Art. 69-B CFF si el proveedor carece de capacidad para $60M anuales, o Art. 49 Bis por inconsistencias en cruces. La defensa requiere: contratos con alcances específicos, minutas de reuniones, correos con avances, presentaciones firmadas, y transferencias trazables. Sin estos, los $5M son gasto no deducible con riesgo penal bajo Art. 113 Bis CFF. Fuente: Art. 27 LISR; Art. 69-B CFF; Art. 113 Bis CFF."),
r("¿Cómo afecta una factura falsa al balance general?",
  "Impacta múltiples líneas: Activo: si corresponde a inventario o activo fijo inexistente, el balance muestra activos que no existen. Al detectarse, se cancelan generando pérdida en resultados. Pasivo: si se registró pero no se pagó, hay pasivo ficticio. Si se pagó, hay egreso real sin contraprestación — posible desfalco. IVA: el IVA acreditado aparece como activo; al revertirlo se convierte en pasivo fiscal con recargos. Capital: la pérdida de deducciones, reversión de IVA y multas reduce el capital contable. En fraudes significativos puede llevar a insolvencia técnica. Fuente: NIF B-6; NIF C-9; Art. 69-B CFF."),
r("What are the key differences between invoice fraud detection in Mexico vs the United States?",
  "Mexico uses a CFDI-centric real-time system: every invoice is a digitally signed XML validated by the SAT, which holds a centralized database of all invoices nationwide. The EFOS/EDOS framework (Art. 69-B CFF) enables retroactive disallowance of all invoices from fraudulent issuers. Criminal penalties reach 9 years (Art. 113 Bis CFF). The US uses a disclosure and audit-based system: no centralized invoice registry — the IRS relies on tax returns, 1099s, and audits. Invoice fraud is caught through IRS audits, whistleblower programs (IRC §7623), or FinCEN SARs. Criminal penalties under IRC §7201 reach 5 years. Key insight: Mexican subsidiary CFDI fraud is immediately visible to SAT; the same fraud in the US might take years to detect. Source: Art. 69-B CFF; IRC §7201; IRC §7623."),
r("¿Qué multa aplica por cancelar una factura fuera de plazo?",
  "La cancelación extemporánea de CFDI genera multa del 5% al 10% del monto de cada factura cancelada fuera de plazo. Si se realizó sin aceptación del receptor cuando era obligatoria, aplican infracciones adicionales bajo Arts. 81 y 83 CFF. Riesgo adicional: una cancelación irregular puede interpretarse como indicio de operación simulada, activando revisión bajo Art. 49 Bis CFF o procedimiento del Art. 69-B. El proceso correcto 2026: verificar si el receptor debe aceptar, emitir CFDI de sustitución si aplica, y hacerlo dentro del ejercicio fiscal. Fuente: Arts. 29, 79, 81, 83 CFF; ContadorMx 2026."),
]

# ── FILE 03: Lavado de Dinero MX ────────────────────────────────────────────
batch_03 = [
r("¿Qué establece el Artículo 400 Bis del Código Penal Federal sobre lavado de dinero en México?",
  "El Art. 400 Bis CPF tipifica el delito de operaciones con recursos de procedencia ilícita (lavado de dinero). Sanciona con 5 a 15 años de prisión y multa de 1,000 a 5,000 días de salario mínimo a quien: adquiera, enajene, administre, custodie, posea, cambie, convierta, deposite, retire, transfiera o traslade recursos, derechos o bienes de procedencia ilícita. El delito aplica sin importar que los actos se realicen en México o en el extranjero. Es un delito autónomo — no requiere que el delito previo haya sido juzgado previamente. La conducta puede ser dolosa o culposa. Fuente: Art. 400 Bis CPF; UIF-SHCP."),
r("¿Cuál es el umbral de reporte de operaciones en efectivo ante la UIF en México?",
  "El umbral principal es de $7,500 USD equivalentes (o $100,000 MXN aproximadamente) para operaciones en efectivo, metales preciosos o divisas. Las entidades financieras deben reportar estas operaciones a la Unidad de Inteligencia Financiera (UIF) de la SHCP dentro de los primeros 10 días hábiles del mes siguiente. Adicionalmente deben reportarse: Operaciones Inusuales (cualquier monto que no corresponda al perfil transaccional del cliente) y Operaciones Preocupantes (conductas del personal). Los Reportes de Operaciones en Efectivo (ROE) aplican también a casas de cambio, notarios y autos de lujo. Fuente: Art. 400 Bis CPF; Ley Federal para la Prevención e Identificación de Operaciones con Recursos de Procedencia Ilícita (LFPIORPI)."),
r("¿Qué son las Actividades Vulnerables bajo la LFPIORPI?",
  "La LFPIORPI (Ley Antilavado de México) establece un catálogo de Actividades Vulnerables cuyos prestadores deben identificar a sus clientes, conservar expedientes y reportar operaciones a la UIF. Las principales actividades son: (1) Juegos con apuesta, concursos y sorteos. (2) Emisión y comercialización de tarjetas de servicios o crédito. (3) Servicios de blindaje de vehículos y bienes inmuebles. (4) Traslado o custodia de dinero o valores. (5) Compraventa de inmuebles por montos >$8,025 UDIS. (6) Compraventa de joyas, relojes, metales preciosos >$805 UDIS. (7) Servicios notariales y de fedatarios. (8) Servicios de contadores públicos en ciertos supuestos. (9) Comercio de vehículos nuevos y usados. (10) Prestación de servicios profesionales independientes. Fuente: Arts. 16-36 LFPIORPI; SAT-UIF."),
r("¿Cuál es la diferencia entre la UIF y el SAT en materia de lavado de dinero?",
  "Son dos autoridades con mandatos distintos pero complementarios. La UIF (Unidad de Inteligencia Financiera, dependiente de la SHCP) es la Unidad de Inteligencia Financiera de México: recibe reportes de entidades financieras y actividades vulnerables, analiza patrones de lavado, genera inteligencia financiera y puede bloquear cuentas bancarias mediante listas negras. El SAT tiene facultades fiscales: detecta discrepancias entre ingresos reportados y estilo de vida/patrimonio, investiga evasión fiscal que puede ser indicio de lavado, y cruza información con la UIF. Cuando una investigación de evasión fiscal revela recursos de origen inexplicable, el expediente se transfiere a la PGR/FGR para investigación penal bajo Art. 400 Bis CPF. Fuente: Art. 400 Bis CPF; LFPIORPI; Ley del SAT."),
r("¿Las tres etapas del lavado de dinero son colocación, estratificación e integración. ¿Cuáles herramientas usa ATLAS para detectarlas?",
  "Correcto en la clasificación. ATLAS detecta señales en cada etapa: Colocación (introducción del dinero ilícito al sistema financiero): depósitos en efectivo en múltiples sucursales por debajo del umbral de reporte (smurfing), mezcla de efectivo con ingresos de negocios de alto manejo de cash. ATLAS cruza ROE de la UIF vs. declaraciones fiscales del contribuyente. Estratificación (ocultamiento del origen mediante transferencias complejas): transferencias entre múltiples cuentas en distintos bancos o países, uso de empresas pantalla, fideicomisos o personas interpuestas. ATLAS mapea redes de transacciones para identificar patrones circulares. Integración (reingreso del dinero al mercado como activos limpios): compra de inmuebles, vehículos de lujo, arte, negocios ficticios con facturas EFOS. ATLAS cruza el patrimonio declarado vs. ingresos fiscales reportados. Fuente: Art. 400 Bis CPF; LFPIORPI; Metodología ATLAS."),
r("Un empresario depositó $80,000 MXN en efectivo en 5 cuentas bancarias distintas el mismo día para evitar el reporte. ¿Esto es legal?",
  "No. Esta conducta se llama smurfing o estructuración y está específicamente tipificada como delito. Dividir depósitos para mantenerse debajo del umbral de $100,000 MXN (equivalente a $7,500 USD) con el fin de evitar el reporte a la UIF es una forma de lavado de dinero bajo el Art. 400 Bis CPF, independientemente del origen de los fondos. Los bancos tienen la obligación de detectar y reportar estas operaciones como Operaciones Inusuales, incluso si cada depósito individual no alcanza el umbral. Adicionalmente, si los fondos provienen de actividad lícita pero se estructuran para evitar reportes, igual constituye el delito. La pena es 5-15 años de prisión. Fuente: Art. 400 Bis CPF; LFPIORPI; Grupo de Acción Financiera Internacional (GAFI)."),
r("¿Qué obligaciones tiene un contador público en México respecto a la LFPIORPI?",
  "Los contadores públicos que presten ciertos servicios profesionales son considerados Actividad Vulnerable bajo la LFPIORPI y tienen obligaciones específicas: (1) Identificar y verificar la identidad de sus clientes (Know Your Customer). (2) Conservar el expediente del cliente por 5 años. (3) Reportar operaciones inusuales o que superen los umbrales a la UIF a través del portal del SAT. (4) No revelar al cliente que fue reportado a la UIF (confidencialidad del reporte). Los servicios que activan estas obligaciones incluyen: administración de recursos del cliente, organización de aportaciones para la constitución o compra de personas morales, administración y enajenación de bienes inmuebles, y manejo de cuentas bancarias o de valores por cuenta del cliente. Fuente: Arts. 17, fracción XVI y 18 LFPIORPI; SAT-UIF 2026."),
r("¿Cuál es la relación entre el delito de evasión fiscal y el lavado de dinero en México?",
  "La evasión fiscal puede ser simultáneamente un delito fiscal (Arts. 108-111 CFF) y el delito previo que alimenta el lavado de dinero (Art. 400 Bis CPF). El esquema típico: una empresa evade ISR usando facturas falsas (EFOS) → los recursos 'ahorrados' en impuestos no pagados son de procedencia ilícita → reinvertirlos en el negocio o en activos constituye lavado. Desde 2020, el delito fiscal grave (evasión superior a $7.8M MXN) es delito previo para lavado de dinero, permitiendo persecución penal simultánea. La UIF y el SAT comparten información para detectar estos esquemas. Una auditoría del SAT que detecta evasión significativa puede derivar en investigación de lavado. Fuente: Arts. 108-111 CFF; Art. 400 Bis CPF; Reforma fiscal 2020."),
r("What is Mexico's Financial Intelligence Unit (UIF) and how does it interact with US FinCEN?",
  "Mexico's UIF (Unidad de Inteligencia Financiera) is the national financial intelligence unit under the SHCP, equivalent to the US Financial Crimes Enforcement Network (FinCEN) under the Treasury Department. Both are members of the Egmont Group, the international network of FIUs that enables information sharing for cross-border money laundering investigations. Interaction mechanisms: (1) Egmont Group secure communications platform for case-specific information exchange. (2) Bilateral Memoranda of Understanding (MOU) for systematic information sharing. (3) FATF (GAFI) mutual evaluation framework — both countries are members. (4) For US-Mexico cross-border cases: FinCEN and UIF can share Suspicious Activity Reports (SARs in the US) and Reportes de Operaciones Inusuales (in Mexico) when there are dual-country transactions. Key distinction: Mexico's UIF can unilaterally freeze bank accounts by listing individuals on a blocking list; the US requires a court order except in cases of OFAC sanctions. Source: LFPIORPI; Bank Secrecy Act; Egmont Group; FATF."),
r("¿Qué pasa si un notario no reporta una operación inmobiliaria sospechosa a la UIF?",
  "El notario incurre en infracciones graves bajo la LFPIORPI. Consecuencias: (1) Multa administrativa de 10,000 a 65,000 días de salario mínimo (aproximadamente $3M a $20M MXN en 2026). (2) Suspensión temporal del ejercicio notarial. (3) En casos de dolo o negligencia grave, posible responsabilidad penal por encubrimiento o complicidad en el delito de lavado (Art. 400 Bis CPF). Los notarios deben reportar a la UIF cuando: el valor del inmueble supera los umbrales de la LFPIORPI, el pago se realiza en efectivo, o existen señales de alerta como terceros pagando por cuenta del comprador real, precios muy por debajo del mercado, o prisa inusual en la operación. Fuente: Arts. 17 fracción XIV y 18 LFPIORPI; Art. 400 Bis CPF."),
]

# ── FILE 04: BSA/AML USA ─────────────────────────────────────────────────────
batch_04 = [
r("¿Qué es el Bank Secrecy Act (BSA) y cuáles son sus principales obligaciones para instituciones financieras en USA?",
  "The Bank Secrecy Act (BSA), enacted in 1970 and codified at 31 USC §5311 et seq., is the primary US anti-money laundering law. It requires financial institutions to assist US government agencies in detecting and preventing money laundering. Core obligations: (1) Currency Transaction Reports (CTRs): file with FinCEN for cash transactions exceeding $10,000 in a single day. (2) Suspicious Activity Reports (SARs): file within 30 days of detecting suspicious activity (no minimum threshold). (3) Customer Identification Program (CIP): verify identity of all customers — name, address, date of birth, ID number. (4) Customer Due Diligence (CDD): understand the nature and purpose of customer relationships and monitor for suspicious activity. (5) Beneficial Ownership: since 2018, identify natural persons owning 25%+ of legal entities. (6) Recordkeeping: maintain records for 5 years. Penalties for non-compliance can reach $1 million per violation plus criminal liability. Source: 31 USC §5311; FinCEN regulations."),
r("¿Cuál es la diferencia entre un CTR y un SAR en el sistema BSA de USA?",
  "Both are mandatory reports to FinCEN, but serve different purposes. CTR (Currency Transaction Report): mandatory when cash transactions exceed $10,000 in a single business day — it is an objective, automatic filing with no judgment required. The threshold is absolute; the institution must file regardless of whether it suspects wrongdoing. SARs (Suspicious Activity Reports): filed when the institution suspects a transaction involves funds from illegal activity, is designed to evade BSA requirements (structuring), or lacks a lawful purpose — with no minimum dollar threshold. SARs require judgment by compliance officers. CTRs are high-volume routine filings; SARs trigger active investigation. Critical rule: never tell the customer you filed a SAR (tipping-off prohibition under 31 USC §5318(g)). Structuring cash deposits below $10,000 to avoid a CTR is itself a federal crime (31 USC §5324). Source: 31 USC §5313 (CTR); 31 USC §5318(g) (SAR); FinCEN."),
r("¿Qué es FATCA y qué obliga a hacer a una empresa mexicana con operaciones en USA?",
  "FATCA (Foreign Account Tax Compliance Act, IRC §1471-1474) requiere que instituciones financieras extranjeras (FFIs) reporten al IRS las cuentas de ciudadanos o residentes fiscales estadounidenses. Para una empresa mexicana con operaciones en USA: (1) Si la empresa tiene cuentas bancarias en USA con titulares o beneficiarios US persons, el banco en USA reportará al IRS automáticamente. (2) Si la empresa mexicana es una FFI (banco, casa de bolsa, aseguradora), debe registrarse ante el IRS, firmar un acuerdo de participación FATCA, y reportar las cuentas de US persons que mantenga. (3) Los pagos de fuente USA a una FFI no participante están sujetos a retención del 30%. Para empresas no financieras mexicanas con empleados o socios US persons: sus cuentas en bancos mexicanos serán reportadas al SAT bajo el acuerdo intergubernamental MX-USA FATCA IGA, y el SAT las transmite al IRS. Fuente: IRC §§1471-1474; FATCA IGA México-USA 2014."),
r("¿Qué es el FBAR y quién está obligado a presentarlo?",
  "The FBAR (FinCEN Form 114, Report of Foreign Bank and Financial Accounts) must be filed by any US person (citizen, resident, or entity organized under US law) who has a financial interest in or signature authority over foreign financial accounts with an aggregate value exceeding $10,000 at any point during the calendar year. Filing deadline: April 15, with automatic extension to October 15. It is filed electronically with FinCEN (not the IRS). The FBAR is separate from and in addition to FATCA reporting on Form 8938. Penalties for non-willful failure: up to $10,000 per violation per year. Willful failure: greater of $100,000 or 50% of the account balance per violation. Criminal penalties: up to 10 years imprisonment. A Mexican executive working for a US company who has authority over a Mexican corporate bank account may have FBAR obligations even if the account has no US-source funds. Source: 31 USC §5314; FinCEN Form 114."),
r("Un cliente dice que no necesita presentar FBAR porque su cuenta en México es solo de la empresa, no personal. ¿Es correcto?",
  "Incorrecto. La obligación de FBAR aplica a US persons que tienen firma autorizada (signature authority) sobre cuentas financieras extranjeras, aunque no tengan interés patrimonial en ellas. Si un ejecutivo estadounidense (US person) es apoderado con firma en una cuenta bancaria de una empresa mexicana, tiene obligación de FBAR si el saldo agregado de todas sus cuentas extranjeras con signature authority supera $10,000 en cualquier momento del año. La excepción existe solo si el ejecutivo ya reportó la cuenta mediante otro mecanismo aprobado por FinCEN. La mayoría de ejecutivos de empresas multinacionales con operaciones en México desconocen esta obligación — es uno de los errores más frecuentes que detecta ATLAS en revisiones de cumplimiento US-MX. Source: 31 USC §5314; FinCEN Form 114; IRS FBAR FAQ."),
r("¿Qué es el USA PATRIOT Act y cómo refuerza las obligaciones AML del BSA?",
  "The USA PATRIOT Act (2001) significantly strengthened the Bank Secrecy Act post-9/11. Key additions relevant to AML: (1) Section 314(a): FinCEN can require financial institutions to search their records for accounts of persons suspected of terrorism or money laundering — mandatory response within 2 weeks. (2) Section 314(b): voluntary information sharing between financial institutions for AML purposes — with FinCEN registration. (3) Enhanced due diligence for foreign correspondent accounts and private banking: must apply additional scrutiny to accounts of foreign banks and high-risk foreign individuals. (4) Customer Identification Program (CIP): codified as mandatory under 31 CFR §1020.220. (5) Prohibition of correspondent accounts for shell banks: banks cannot maintain accounts for foreign shell banks (those with no physical presence). For cross-border MX-USA operations, Section 311 Special Measures can designate Mexican financial institutions as primary money laundering concerns, restricting US correspondent banking. Source: USA PATRIOT Act §§311, 314(a)(b); 31 USC §5318."),
r("¿Cuál es la exposición legal de una empresa mexicana que realiza pagos en efectivo a sus trabajadores en USA?",
  "Múltiple exposición. En el ámbito BSA/AML: pagos de nómina en efectivo superiores a $10,000 en un día generan obligación de CTR para el banco. Patrones de retiros de efectivo para nómina sin documentación suficiente pueden activar un SAR. En el ámbito fiscal IRS: los pagos a trabajadores deben reportarse en Form W-2 (empleados) o 1099-NEC (contratistas). Pagos en efectivo sin reporte fiscal constituyen evasión bajo IRC §7201 y pueden ser indicios de trabajo no autorizado. En el ámbito laboral: el IRS y el Department of Labor coordinan auditorías para detectar trabajadores pagados en efectivo fuera de nómina. Riesgo adicional de FBAR: si la empresa tiene cuentas en México desde las que transfiere efectivo para pagos en USA sin documentación, puede activar señales de lavado. ATLAS recomienda nunca usar efectivo para nómina — usar ACH, cheque o tarjeta de débito empresarial. Source: BSA 31 USC §5313; IRC §7201; Form W-2; Form 1099-NEC."),
r("¿Qué información debe incluir un SAR (Suspicious Activity Report) presentado ante FinCEN?",
  "A SAR must be filed on FinCEN Form 114 (SAR) and must include: (1) Identity of the subject: name, address, SSN/ITIN/EIN, date of birth, account number. (2) Description of suspicious activity: what happened, how much, over what time period, why it is suspicious. (3) Supporting documentation: transaction records, account statements, correspondence — retained for 5 years but not attached to the SAR. (4) Financial institution information: name, address, contact person. Filing deadline: 30 calendar days from the date suspicious activity is initially detected; 60 days if no suspect can be identified. The SAR is confidential — disclosure to the subject (tipping off) is a federal crime under 31 USC §5318(g)(2). Safe harbor: institutions filing in good faith are protected from civil liability. Source: 31 USC §5318(g); FinCEN SAR regulations 31 CFR §1020.320."),
r("¿Qué es el OCC y qué rol tiene en la supervisión AML de bancos en USA?",
  "The OCC (Office of the Comptroller of the Currency) is the primary federal regulator for national banks and federal savings associations in the US. Its AML role: (1) Conducts regular BSA/AML compliance examinations of national banks — assesses the quality of AML programs, CTR/SAR filings, and KYC/CDD procedures. (2) Issues enforcement actions for BSA violations: Cease and Desist orders, Civil Money Penalties (CMPs) up to $1 million per day per violation. (3) Coordinates with FinCEN, FDIC, Federal Reserve, and state regulators through the Federal Financial Institutions Examination Council (FFIEC) BSA/AML Examination Manual — the definitive reference for bank AML compliance. For Mexican banks with US correspondent relationships: OCC can restrict or terminate correspondent accounts if the Mexican bank's AML program is deemed insufficient. Source: 12 USC §1; OCC BSA/AML Examination Manual; FFIEC."),
r("¿Cómo debe documentar una empresa mexicana sus transacciones en USA para evitar reportes de actividad sospechosa?",
  "La clave no es 'evitar' reportes SAR sino tener un perfil transaccional coherente y documentado. ATLAS recomienda: (1) Establecer desde el inicio de la relación bancaria un perfil de negocio claro: industria, volumen esperado de transacciones, tipos de clientes, origen de fondos. (2) Documentar cada transacción significativa: contratos, facturas, órdenes de compra — los mismos principios de materialidad que aplican en México. (3) Evitar cambios abruptos en patrones sin notificar al banco: si el volumen mensual típico es $50K y un mes es $500K, notifica proactivamente con documentación. (4) Nunca estructurar depósitos para mantenerse bajo $10,000 — es delito federal (31 USC §5324). (5) Mantener los mismos estándares de due diligence sobre tus propios clientes en USA. Un banco en USA que no puede entender el propósito de las transacciones de un cliente mexicano puede cerrar la cuenta por riesgo — se llama de-risking. Source: BSA 31 USC; FinCEN; OCC Guidance."),
]

all_batches = batch_02 + batch_03 + batch_04

with open(OUT, "a", encoding="utf-8") as f:
    for record in all_batches:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

print(f"Appended {len(all_batches)} records (files 02-04)")
print(f"  batch_02: {len(batch_02)}")
print(f"  batch_03: {len(batch_03)}")
print(f"  batch_04: {len(batch_04)}")
