import json

OUT = r"D:\Proyectos\atlas-amd-hackathon\Trainning_Steps\atlas_training_dataset_v3.jsonl"
SYS = ("Eres ATLAS, auditor forense especializado en regulaciones financieras MX-USA. "
       "Responde con precisión legal, citando artículos y fuentes oficiales. "
       "Usa razonamiento paso a paso cuando el caso lo requiera. "
       "Si detectas una premisa falsa en la pregunta, corrígela explícitamente antes de responder.")

def r(u, a):
    return {"messages":[{"role":"system","content":SYS},{"role":"user","content":u},{"role":"assistant","content":a}]}

# ── FILE 05: CFDI 4.0 ─────────────────────────────────────────────────────────
batch_05 = [
r("¿Cuáles son los cuatro motivos válidos de cancelación de CFDI en 2026?",
  "El SAT permite exactamente cuatro motivos de cancelación en 2026: Clave 01 - Comprobante con errores con relación: hay errores en la factura pero se emite una nueva que la sustituye (requiere relacionar el UUID del CFDI cancelado con el nuevo). Clave 02 - Comprobante con errores sin relación: hay errores irreparables y no se emite factura sustituta. Clave 03 - No se llevó a cabo la operación: la venta o servicio nunca ocurrió. Clave 04 - Operación nominativa en factura global: la venta al público general que requiere factura individual ya fue incluida en una factura global. Usar el motivo incorrecto genera multa del 5-10% del monto. Fuente: Art. 29-A CFF; RMF 2026; Upseller Guía Cancelación."),
r("¿Hasta cuándo puedo cancelar una factura de 2025 siendo persona moral?",
  "Como persona moral con cierre fiscal en diciembre, tienes hasta el 31 de marzo de 2026 para cancelar CFDIs del ejercicio 2025. Este plazo corresponde al mes en que debes presentar tu declaración anual de ISR. Es el límite que establece el Art. 29-A CFF: la cancelación debe realizarse a más tardar en el mes en que se presenta la declaración anual del ejercicio en que se emitió el comprobante. Personas físicas tienen hasta el 30 de abril. Cancelar después de este plazo genera multa del 5% al 10% del monto del CFDI cancelado. Fuente: Art. 29-A CFF; RMF 2026; ContadorMx."),
r("¿El receptor de una factura puede rechazar mi solicitud de cancelación?",
  "Sí. El procedimiento de cancelación notifica al receptor vía Buzón Tributario y le da 3 días hábiles para aceptar o rechazar. Si no responde, se aplica aceptación tácita (el CFDI queda cancelado automáticamente). Sin embargo, hay casos que SIEMPRE requieren aceptación expresa y no aplica la aceptación tácita: CFDIs con Complemento de Recepción de Pagos (CRP/REP), CFDIs de hidrocarburos/Carta Porte con combustibles (gasolina o diésel). Si el receptor rechaza la cancelación y tu motivo es legítimo, puedes presentar aclaración ante el SAT. Un rechazo injustificado por parte del receptor no te obliga a mantener el CFDI vigente si la operación no ocurrió. Fuente: Art. 29-A CFF; RMF 2026; Upseller."),
r("¿Por qué en 2026 ya no puedo cancelar sin aceptación un CFDI con complemento de pago, aunque sea menor de $1,000?",
  "Correcto — es un cambio importante de la RMF 2026. Antes, los CFDIs menores de $1,000 podían cancelarse sin aceptación del receptor. Desde 2026, los CFDIs con Complemento de Recepción de Pagos (CRP/REP) están EXCLUIDOS de esta facilidad, independientemente del monto. La razón: el CRP/REP documenta pagos efectivamente realizados — cancelarlo sin acuerdo del receptor afectaría la integridad del registro de pagos y podría usarse para manipular el flujo de efectivo reportado. Esta medida protege tanto al receptor como al SAT de cancelaciones maliciosas de comprobantes de pago ya aplicados. También aplica la misma restricción para CFDIs de hidrocarburos y Carta Porte con combustibles. Fuente: RMF 2026; ContadorMx; EY CFDI 4.0."),
r("¿Qué pasa si un contribuyente emite CFDIs a nombre de un RFC que no le corresponde?",
  "Es una de las causales de restricción temporal del CSD bajo el Art. 17-H Bis CFF, fracción relacionada con el Art. 79 CFF. El SAT puede suspender inmediatamente el CSD sin previo aviso. Adicionalmente: constituye infracción bajo el Art. 83 CFF con multas específicas, puede ser indicio de operación simulada activando procedimiento del Art. 69-B CFF, y en casos de dolo puede constituir el delito del Art. 113 Bis CFF (prisión 2-9 años). En CFDI 4.0 el SAT valida en tiempo real que el RFC del receptor sea activo y que el régimen fiscal sea compatible con la operación declarada — por lo que este error generalmente se detecta antes de la emisión. Sin embargo, si el sistema lo dejó pasar, la responsabilidad es del emisor. Fuente: Arts. 17-H Bis, 79, 83 CFF; Art. 113 Bis CFF; Ficachi."),
r("¿Qué nuevas validaciones de materialidad introdujo el SAT en CFDI 4.0 para 2026?",
  "Las nuevas validaciones de operación en CFDI 4.0 para 2026 van más allá de la validación técnica del XML: (1) Precios unitarios vs. mercado: el SAT contrasta los precios declarados contra datos de mercado para detectar valores inflados o deflados artificialmente. (2) Cantidades vs. capacidad operativa: el volumen facturado se cruza contra los activos y personal registrados del emisor en el SAT. (3) Relación emisor-receptor según giros: una empresa de limpieza que factura servicios de ingeniería aeroespacial activará una alerta. (4) Fechas coherentes con el período fiscal: facturas con fechas inconsistentes con el ciclo operativo normal. Estas validaciones pueden activar el procedimiento del Art. 49 Bis CFF y la suspensión del CSD. Fuente: Art. 49 Bis CFF; Proceso.mx 2026; SAT."),
r("Un proveedor me pide que acepte la cancelación de una factura de $500,000 MXN que ya pagué. ¿Qué riesgo tengo si acepto?",
  "Alto riesgo. Si aceptas la cancelación de una factura ya pagada sin recibir una factura sustituta o la devolución del dinero: (1) Pierdes la deducción de ese gasto en ISR — el CFDI ya no existe como respaldo. (2) Pierdes el IVA acreditado de esa factura — puede generarte IVA a cargo. (3) El pago que realizaste queda sin documentación fiscal, lo que puede interpretarse como un pago sin comprobante, generando problemas en tu contabilidad y auditorías futuras. Lo correcto: si hay errores en la factura, el proveedor debe emitir una nota de crédito o una factura sustituta (clave 01) antes de que aceptes la cancelación, o hacer la cancelación y una nueva emisión simultáneamente. Si ya pagaste y no hay devolución ni sustitución, no aceptes la cancelación. Fuente: Art. 29-A CFF; Art. 27 LISR."),
r("¿Qué es el Complemento Concepto para Hidrocarburos y Petrolíferos creado en 2026?",
  "Es un complemento obligatorio nuevo en CFDI 4.0 para ciertos contribuyentes del sector de hidrocarburos y petrolíferos. Fue creado en la RMF 2026 para incrementar el control sobre las operaciones de este sector, históricamente con alto riesgo de facturación irregular (huachicol, gasolina robada). Sus características: (1) Es obligatorio para operaciones específicas del sector. (2) Los CFDIs con este complemento, así como los de Carta Porte que incluyan combustibles (gasolina o diésel), SOLO pueden cancelarse con aceptación expresa del receptor — no aplica aceptación tácita. (3) Esta medida busca prevenir cancelaciones unilaterales de facturas de combustibles que podrían usarse para encubrir robo de hidrocarburo. Fuente: RMF 2026; ContadorMx; EY CFDI 4.0."),
r("¿Puedo emitir facturas a RFC XAXX010101000 en RESICO sin límite?",
  "No. El RFC genérico XAXX010101000 (público en general) tiene límites importantes en el RESICO. Para personas físicas en RESICO: solo puede usarse en operaciones con el público en general donde el cliente no requiere factura fiscal. Sin embargo, la RMF 2026 establece límites de monto por operación para usar RFC genérico — superar esos umbrales obliga a solicitar el RFC real del cliente. Adicionalmente, el volumen de facturación a XAXX010101000 es un indicador de riesgo que monitorea ATLAS — una empresa que factura el 90% a RFC genérico pero declara millones en ingresos activa alertas de evasión. En el sector minorista es normal; en servicios profesionales o B2B es una señal crítica. Fuente: LISR Arts. 113-A y siguientes RESICO; RMF 2026."),
r("¿Qué campos adicionales obligatorios tiene el CFDI 4.0 que no existían en versiones anteriores?",
  "CFDI 4.0 introdujo campos obligatorios que no existían en 3.3: (1) Domicilio fiscal del receptor: código postal que debe coincidir con el domicilio registrado ante el SAT — antes solo se requería el RFC. (2) Exportación: campo que indica si la operación es de exportación (A01 definitiva, A02 temporal, etc.) o no (A04). (3) Objeto de impuesto: especifica si la operación es objeto de impuesto (01 No objeto, 02 Sí objeto, 03 Sí objeto pero no obligado al desglose). (4) Periodicidad y meses: requerido para CFDIs de nómina, indica el período cubierto. (5) Régimen fiscal del receptor: antes opcional, ahora obligatorio y validado en tiempo real contra el SAT. Estos campos permiten al SAT validar automáticamente la coherencia de cada factura con el perfil fiscal del emisor y receptor. Fuente: SAT Anexo 20; RMF 2026."),
]

# ── FILE 06: RESICO ────────────────────────────────────────────────────────────
batch_06 = [
r("¿Qué sucede si un contribuyente en RESICO omite 3 pagos mensuales en un año?",
  "La omisión de 3 o más pagos mensuales de ISR en el RESICO dentro de un año calendario (consecutivos o no) es una causal de restricción temporal del CSD bajo el Art. 17-H Bis CFF. Consecuencias: (1) El SAT notifica la restricción vía Buzón Tributario. (2) El contribuyente no puede emitir CFDIs válidos mientras dure la restricción. (3) Sin CSD vigente, los ingresos no se pueden documentar fiscalmente. Para levantar la restricción: pagar los importes omitidos con actualizaciones y recargos, y presentar los descargos ante el SAT demostrando que se subsanó el incumplimiento. Si la restricción no se levanta, puede convertirse en cancelación definitiva del CSD bajo Art. 17-H CFF. Fuente: Art. 17-H Bis CFF; Arts. 113-A y siguientes LISR RESICO; Ficachi Boletín 64/2024."),
r("¿Cuál es la diferencia entre el Art. 17-H y el Art. 17-H Bis del CFF?",
  "Es una distinción crítica: el Art. 17-H CFF establece la CANCELACIÓN DEFINITIVA del CSD — es irreversible y el contribuyente pierde permanentemente la capacidad de emitir CFDIs bajo ese RFC. El Art. 17-H Bis CFF establece la RESTRICCIÓN TEMPORAL del CSD — es reversible si el contribuyente subsana las irregularidades que la causaron dentro del plazo otorgado. El 17-H Bis es una medida preventiva; el 17-H es sancionatoria definitiva. Un contribuyente que no atiende una restricción temporal del 17-H Bis puede escalar a cancelación definitiva del 17-H. La defensa ante el 17-H Bis es aclarar y pagar; ante el 17-H requiere impugnación legal. Fuente: Arts. 17-H y 17-H Bis CFF; RMF 2026; Ficachi."),
r("Soy persona física en RESICO con ingresos de $3.5M anuales. ¿Puedo seguir en este régimen?",
  "Depende del límite vigente en 2026. El RESICO para personas físicas tiene un límite máximo de ingresos anuales establecido en la LISR — superar ese límite obliga al cambio de régimen. Necesitas verificar el monto exacto en la RMF 2026 y la LISR vigente, ya que los límites se actualizan por inflación. Si tus ingresos superan el umbral, debes presentar el aviso de cambio de régimen ante el SAT dentro del plazo establecido. No hacerlo genera: multas por no avisar al RFC (Art. 79 CFF), posible determinación de diferencias de ISR si el RESICO tiene tasas menores al régimen general que correspondía, y restricción del CSD. Verifica el límite exacto en sat.gob.mx o con tu asesor fiscal antes de presentar declaraciones. Fuente: LISR Arts. 113-A y siguientes; Art. 17-H Bis CFF; RMF 2026."),
r("¿Qué es la DIOT y qué pasa si no la presento en RESICO?",
  "La DIOT (Declaración Informativa de Operaciones con Terceros) reporta al SAT los pagos realizados a proveedores con IVA. En el RESICO, la obligación de presentar DIOT depende del nivel de ingresos y modalidad específica del régimen. Si estás obligado y no la presentas: es una infracción bajo el Art. 81 CFF, puede generar restricción temporal del CSD bajo el Art. 17-H Bis, y es un red flag que activa mayor escrutinio del SAT sobre tus compras y proveedores. Adicionalmente, el no presentar DIOT dificulta al SAT cruzar tu IVA acreditable contra los ingresos reportados por tus proveedores — cuando el SAT detecta esta inconsistencia, puede presumir que las deducciones son infladas. Fuente: Arts. 81 CFF; Art. 17-H Bis CFF; LFIVA."),
r("¿Qué documentos debe conservar un contribuyente en RESICO para una auditoría?",
  "Los contribuyentes en RESICO deben conservar por 5 años (Art. 30 CFF) toda la documentación que respalde sus ingresos y deducciones: CFDIs emitidos y recibidos en formato XML original (no solo PDF), estados de cuenta bancarios que muestren los flujos reales de operación, contratos con clientes y proveedores, comprobantes de pago de impuestos (ISR mensual, IVA), constancias de situación fiscal de proveedores principales, evidencia de materialidad de gastos significativos (órdenes de compra, recibos de entrega), y registros de contabilidad electrónica si estás obligado a llevarla. El RESICO no exime del respaldo documental — simplifica el cálculo del impuesto, no los requisitos de materialidad. Fuente: Art. 30 CFF; Art. 27 LISR; RMF 2026."),
r("¿Cómo puede una empresa proveedora operar si su CSD fue restringido por el SAT?",
  "Con el CSD restringido, la empresa NO puede emitir CFDIs válidos — esto es una parálisis operativa total en la economía formal mexicana. Sus opciones inmediatas son: (1) Resolver la causal de restricción: revisar la notificación del SAT en el Buzón Tributario para identificar el motivo específico, subsanar el incumplimiento (pagar omisiones, corregir errores), y solicitar la liberación del CSD aportando los comprobantes. (2) Si hay error del SAT: presentar aclaración dentro del plazo indicado con documentación que demuestre que sí cumplió las obligaciones señaladas. (3) Medida cautelar urgente: si el daño es irreversible (pérdida de contratos), puede solicitarse una suspensión ante el Tribunal Federal de Justicia Administrativa. Lo que NO debe hacerse: intentar facturar usando otro RFC o mediante terceros — eso agrava la situación y puede configurar el delito del Art. 113 Bis CFF. Fuente: Arts. 17-H y 17-H Bis CFF; RMF 2026; Ficachi."),
r("¿Puede el SAT restringir el CSD por no enviar la contabilidad electrónica?",
  "Sí. No enviar la contabilidad electrónica al SAT cuando se está obligado a hacerlo es una infracción bajo el Art. 81 CFF, y es causal de restricción temporal del CSD bajo el Art. 17-H Bis. La obligación de contabilidad electrónica aplica a personas morales y a personas físicas con ingresos superiores a ciertos umbrales. El SAT recibe la contabilidad electrónica mensualmente (catálogo de cuentas, balanza de comprobación) y anualmente (pólizas en caso de auditoría). No enviarla equivale a negar información al SAT sobre el estado financiero del contribuyente — la restricción del CSD es la respuesta proporcional para presionar el cumplimiento. Fuente: Art. 81 CFF fracción específica; Art. 17-H Bis CFF; Art. 28 CFF (contabilidad electrónica)."),
r("¿Qué diferencia hay entre RESICO personas físicas y RESICO personas morales?",
  "Son regímenes distintos aunque comparten el nombre. RESICO personas físicas (Arts. 113-A a 113-J LISR): para actividades empresariales, profesionales y arrendamiento con ingresos por debajo del límite anual. Tasas progresivas de ISR reducidas. Declaraciones mensuales simplificadas. No requiere llevar contabilidad electrónica en niveles bajos de ingresos. RESICO personas morales: para ciertos tipos de personas morales (no incluye grandes corporativos). Tasas de ISR también reducidas respecto al régimen general. Obligaciones similares al régimen general pero con simplificaciones administrativas. Sí requiere contabilidad electrónica. La confusión más común: un contribuyente persona física que constituye una S.A. o S. de R.L. cree que puede aplicar el RESICO de personas físicas — no puede, debe aplicar el de personas morales (si califica) o el régimen general. Fuente: Arts. 113-A y siguientes LISR; RMF 2026."),
r("¿Registrar gastos inexistentes en la contabilidad puede causar restricción del CSD?",
  "Sí, directamente. El Art. 83 CFF tipifica como infracción registrar gastos inexistentes en la contabilidad. Esto es causal de restricción temporal del CSD bajo el Art. 17-H Bis. Pero las consecuencias van más allá de la restricción del CSD: (1) Si los gastos inexistentes están respaldados por CFDIs de EFOS, el Art. 69-B CFF activa pérdida de deducibilidad y reversión de IVA. (2) Si hay dolo, puede configurarse el delito del Art. 113 Bis CFF (prisión 2-9 años). (3) Si los montos son significativos, puede derivar en investigación de lavado de dinero bajo el Art. 400 Bis CPF. La contabilidad electrónica enviada al SAT se cruza automáticamente contra los CFDIs emitidos y recibidos — las discrepancias son detectadas algorítmicamente. Fuente: Art. 83 CFF; Art. 17-H Bis CFF; Art. 69-B CFF; Art. 113 Bis CFF."),
r("¿El RESICO elimina la obligación de verificar que los proveedores no estén en listas EFOS?",
  "No. El RESICO simplifica el cálculo del ISR y algunas obligaciones formales, pero NO elimina la obligación de due diligence sobre proveedores ni la responsabilidad como EDOS. Si un contribuyente en RESICO deduce gastos de un proveedor EFOS definitivo: pierde la deducibilidad de esas facturas, debe revertir el IVA acreditado, y enfrenta créditos fiscales con multas. El Art. 69-B CFF aplica igual a contribuyentes en RESICO que en régimen general. ATLAS recomienda a todos los contribuyentes, independientemente de su régimen, verificar a sus proveedores en las listas del SAT antes de realizar pagos significativos y mantener el due diligence actualizado. Fuente: Art. 69-B CFF; Arts. 113-A y siguientes LISR RESICO."),
]

# ── FILE 07: NIF vs IFRS ───────────────────────────────────────────────────────
batch_07 = [
r("¿Cuál es la diferencia principal entre el modelo de reconocimiento de ingresos NIF D-1 e IFRS 15?",
  "La diferencia conceptual central es el enfoque: la NIF D-1 (México, CINIF) basa el reconocimiento de ingresos en la transferencia de riesgos y beneficios al cliente — un modelo orientado a principios generales que permite interpretaciones según la naturaleza de la empresa. El IFRS 15 (IASB) usa un modelo estructurado de 5 pasos centrado en la transferencia de CONTROL al cliente: (1) Identificar el contrato, (2) Identificar las obligaciones de desempeño, (3) Determinar el precio de la transacción, (4) Asignar el precio a las obligaciones, (5) Reconocer el ingreso cuando se satisface cada obligación. En la práctica, ambos modelos llegan a conclusiones similares en la mayoría de transacciones simples, pero difieren en contratos complejos, servicios de largo plazo, y contratos con componentes de financiamiento. Fuente: NIF D-1 CINIF; IFRS 15 IASB; GSG Consultores."),
r("¿Pueden las empresas mexicanas aplicar IFRS en lugar de NIF?",
  "Depende de la entidad. Las NIF son obligatorias en México para la mayoría de entidades privadas. Sin embargo: las empresas listadas en la Bolsa Mexicana de Valores (BMV) tienen la opción de presentar estados financieros bajo IFRS para fines de la BMV, además de mantener contabilidad bajo NIF para efectos fiscales. Las subsidiarias mexicanas de grupos multinacionales típicamente preparan: estados financieros locales bajo NIF (para SAT y obligaciones legales) y estados financieros de reporte bajo IFRS o US GAAP (para consolidación con la matriz). No es una elección libre — el SAT requiere NIF para efectos fiscales, independientemente de si la empresa también reporta bajo IFRS. Fuente: CINIF; Comisión Nacional Bancaria y de Valores (CNBV); NIF A-1."),
r("¿Cómo afectan las diferencias entre NIF e IFRS a los precios de transferencia de una empresa mexicana?",
  "Las diferencias contables pueden crear problemas en el análisis de precios de transferencia: (1) Base de costos: si la empresa mexicana deprecia activos bajo NIF y la comparable usa IFRS con componentización obligatoria, los márgenes de costo no son directamente comparables. (2) Márgenes de utilidad: la NIF permite revaluación de activos (lo que afecta la depreciación y los márgenes), mientras US GAAP lo prohíbe — un ajuste de comparabilidad es necesario. (3) Reconocimiento de ingresos: diferencias en timing de reconocimiento bajo NIF D-1 vs IFRS 15 pueden distorsionar los ratios de rentabilidad en periodos específicos. (4) Arrendamientos: NIF D-5 e IFRS 16 tienen modelo único (todo en balance), pero US GAAP ASC 842 tiene modelo dual — afecta ratios de deuda y EBITDA. La documentación de precios de transferencia debe explicar y ajustar estas diferencias. Fuente: NIF D-1, D-5; IFRS 15, 16; IAS 16; OCDE TP Guidelines."),
r("¿Qué es la componentización de activos fijos y por qué es obligatoria bajo IFRS pero no bajo NIF?",
  "La componentización (IAS 16) obliga a depreciar por separado los componentes significativos de un activo fijo que tengan vidas útiles distintas. Ejemplo: un avión debe depreciar por separado el fuselaje (25 años), los motores (15 años), el interior de la cabina (10 años) y los neumáticos (2 años) — porque reemplazarlos no tiene la misma vida útil. Bajo IFRS (IAS 16): es obligatorio cuando los componentes son significativos y tienen vidas útiles diferentes. Bajo NIF (México): está permitida pero no es obligatoria. La diferencia práctica: una empresa que aplica IFRS tendrá gastos de depreciación más altos en los primeros años (componentes de vida corta se deprecian más rápido) y reconocerá la sustitución de componentes como un activo nuevo en lugar de gasto. Bajo NIF, muchas empresas tratan el activo como una unidad, subestimando el costo real de uso. Fuente: IAS 16; NIF C-6; GSG Consultores."),
r("¿Qué diferencia existe entre US GAAP y NIF en el tratamiento de la revaluación de activos fijos?",
  "Es una diferencia fundamental: bajo US GAAP (ASC 360), la revaluación de activos fijos está COMPLETAMENTE PROHIBIDA — los activos siempre se registran a costo histórico menos depreciación acumulada, sin importar su valor de mercado. Bajo NIF (México) e IFRS (IAS 16): se permite el modelo de revaluación como política contable, reconociendo los activos a valor razonable. Los incrementos por revaluación van a Otro Resultado Integral (ORI) en el patrimonio; las disminuciones van a resultados. Esta diferencia es crítica para empresas mexicanas con matrices en USA que consolidan bajo US GAAP: deben reversar la revaluación en la conversión a US GAAP. También afecta los ratios de precios de transferencia — la base de activos para calcular el ROCE (Return on Capital Employed) difiere significativamente. Fuente: US GAAP ASC 360; IAS 16; NIF C-6; GSG Consultores."),
r("¿En qué se diferencia NIF D-5 de IFRS 16 en el tratamiento de arrendamientos?",
  "Conceptualmente ambas normas son muy similares — implementan el modelo único donde prácticamente todos los arrendamientos se reconocen en el balance del arrendatario como un activo por derecho de uso y un pasivo por arrendamiento. Diferencias de detalle: NIF D-5 es la versión mexicana basada en los principios de IFRS 16, adaptada al contexto local. IFRS 16 tiene guías más detalladas para casos específicos como arrendamientos de activos de bajo valor, modificaciones de contratos, y combinaciones de negocios. La diferencia importante es contra US GAAP ASC 842: mientras NIF D-5 e IFRS 16 tienen modelo único, US GAAP mantiene la distinción entre arrendamientos operativos y financieros para la presentación en el estado de resultados — lo que afecta el EBITDA (los arrendamientos operativos bajo US GAAP se muestran en un solo renglón; bajo IFRS se dividen en depreciación e intereses). Fuente: NIF D-5; IFRS 16; US GAAP ASC 842; GSG Consultores."),
r("¿Qué son las Mejoras a las NIF 2025 y cuándo entran en vigor?",
  "Las Mejoras a las NIF 2025, publicadas por el CINIF, entraron en vigor para ejercicios iniciados a partir del 1 de enero de 2025, con aplicación anticipada permitida para el ejercicio 2024. Los cambios más relevantes incluyen: NIF B-16: modificación al párrafo 52.2.2 sobre presentación de ingresos. NIF C-3: modificaciones sobre presentación de bonificaciones, descuentos, devoluciones y fluctuaciones cambiarias. NIF C-6: actualización de métodos de depreciación. NIF B-1: regula cómo contabilizar los cambios contables que surjan de la aplicación de estas mejoras. El objetivo de las Mejoras NIF 2025 es continuar la convergencia con los estándares internacionales IFRS, reduciendo las diferencias que actualmente deben reconciliarse por empresas con doble reporte. Fuente: CINIF Mejoras NIF 2025; cinif.org.mx."),
r("¿Cuál es el impacto fiscal de la revaluación de activos bajo NIF en México?",
  "Aquí hay una brecha importante entre la contabilidad y los impuestos. La revaluación de activos bajo NIF incrementa el valor contable del activo y genera una reserva de revaluación en el patrimonio (ORI). Sin embargo, para efectos fiscales en México: la LISR no reconoce la revaluación contable como base de depreciación fiscal. La depreciación deducible para ISR se calcula sobre el costo de adquisición histórico, aplicando los porcentajes del Art. 34 LISR, no sobre el valor revaluado. Esto crea una diferencia temporaria entre la depreciación contable (mayor, sobre valor revaluado) y la depreciación fiscal (menor, sobre costo histórico), generando un activo por impuesto diferido bajo NIF D-4. Las empresas deben asegurarse de no deducir la depreciación sobre el valor revaluado — es un error que puede generar un crédito fiscal del SAT. Fuente: Art. 34 LISR; NIF C-6; NIF D-4."),
r("Un CFO de empresa multinacional dice que su subsidiaria mexicana puede reportar bajo IFRS porque su matriz es europea. ¿Es correcto?",
  "Parcialmente correcto, con matiz crítico: la subsidiaria mexicana PUEDE preparar estados financieros de reporte bajo IFRS para fines de consolidación con la matriz europea. Sin embargo, para efectos fiscales ante el SAT, la contabilidad DEBE estar bajo NIF. El SAT acepta NIF como marco contable fiscal — no acepta IFRS directamente para calcular ISR, IVA ni otros impuestos. En la práctica, la subsidiaria mantiene dos sets de registros: (1) Libros fiscales-contables bajo NIF para el SAT, declaraciones de impuestos y obligaciones legales en México. (2) Reporte de consolidación bajo IFRS para la matriz europea con los ajustes de conversión correspondientes. Las diferencias NIF vs IFRS deben estar documentadas para precios de transferencia y para auditorías del SAT que soliciten la conciliación entre ambos marcos. Fuente: CINIF NIF A-1; LISR; SAT; CNBV."),
r("¿Cuál es el tratamiento de las pérdidas esperadas de crédito bajo NIF vs IFRS 9?",
  "Es una diferencia relevante en proceso de convergencia. IFRS 9 introdujo el modelo de Expected Credit Losses (ECL): la entidad debe reconocer pérdidas crediticias esperadas desde el origen del activo financiero, usando un modelo de 12 meses para activos sin deterioro significativo y pérdidas esperadas de vida completa (lifetime ECL) cuando hay deterioro. US GAAP implementó CECL (Current Expected Credit Loss), aún más conservador: reconoce todas las pérdidas esperadas de vida completa desde el inicio. NIF en México: está en proceso de alineación con estándares internacionales pero históricamente ha usado modelos de pérdidas incurridas (solo reconoces cuando hay evidencia objetiva de deterioro). La transición al modelo ECL implica reconocer mayores provisiones anticipadas, reduciendo utilidades del período de transición. Para empresas con carteras de crédito significativas, esta diferencia puede ser material en estados financieros comparativos. Fuente: IFRS 9; US GAAP ASC 326; CINIF proceso de mejoras."),
]

# ── FILE 08: Multi-Jurisdicción ────────────────────────────────────────────────
batch_08 = [
r("¿Cuándo se firmó el Convenio para Evitar la Doble Tributación entre México y Estados Unidos?",
  "El Convenio fue firmado el 18 de septiembre de 1992. El Protocolo de 1994 amplió su alcance para incluir impuestos estatales y locales de Estados Unidos. El convenio sigue vigente y aplica a residentes de ambos países. Cubre el ISR en México y el Income Tax federal en USA (más impuestos estatales y locales por el Protocolo 1994). Sus principios fundamentales son: asignación de derechos de tributación entre ambos países, mecanismos para eliminar la doble tributación (principalmente el método del crédito fiscal), y prevención de evasión y elusión fiscal. Es el instrumento central que regula la tributación de dividendos, intereses, regalías y servicios entre entidades MX-USA. Fuente: CDI México-USA 1992; Protocolo 1994; IRS Tax Treaties."),
r("¿Qué es el treaty shopping y cómo lo combate el CDI México-USA?",
  "El treaty shopping es la práctica de estructurar operaciones a través de jurisdicciones con convenios fiscales favorables para reducir impuestos, sin tener presencia económica real en esa jurisdicción. Ejemplo: una empresa de un tercer país crea una entidad en México solo para acceder a las tasas reducidas del CDI México-USA en dividendos (10% vs. 30% de retención estándar). El CDI México-USA incluye una cláusula de Limitación de Beneficios (LOB - Limitation on Benefits) que exige cumplir tests para acceder a los beneficios del convenio: (1) Test de propiedad: porcentaje mínimo de accionistas residentes del país contratante. (2) Test de actividad comercial: realización de actividad sustancial en el país de residencia. (3) Test de tráfico activo: para empresas de transporte. Si no se cumplen los tests, el SAT o el IRS pueden negar los beneficios del convenio. Fuente: CDI México-USA Arts. 17-17A; BEPS Acción 6."),
r("¿Qué tasa de retención aplica el CDI México-USA sobre dividendos?",
  "El CDI México-USA establece dos tasas máximas de retención en la fuente sobre dividendos: 10% cuando el beneficiario efectivo es una empresa que posee directamente al menos el 10% de las acciones con derecho a voto de la empresa que paga los dividendos. 15% en todos los demás casos. Estas tasas son menores a la retención estándar que aplicaría sin convenio. Importante: para acceder a estas tasas reducidas el beneficiario debe ser residente fiscal del otro Estado contratante y cumplir con la cláusula LOB del convenio. Si la estructura involucra una empresa conduit (sin sustancia real) creada solo para acceder al convenio, el SAT o el IRS pueden aplicar la tasa ordinaria más alta. Fuente: CDI México-USA Art. 10; IRS Publication 515; SAT."),
r("¿Cuándo constituye un establecimiento permanente (EP) en México una empresa estadounidense?",
  "Una empresa estadounidense tiene Establecimiento Permanente (EP) en México cuando: (1) Tiene un lugar fijo de negocios en México a través del cual realiza su actividad: oficinas, sucursales, fábricas, talleres, minas, canteras. (2) Tiene una agencia dependiente: una persona en México con poderes para concluir contratos en nombre de la empresa. El CDI México-USA excluye del EP: uso de instalaciones solo para almacenamiento, exhibición o entrega de mercancías, mantenimiento de stock para procesamiento por otra empresa, y actividades preparatorias o auxiliares. Consecuencia del EP: la empresa estadounidense debe tributar en México sobre las rentas atribuibles al EP bajo las reglas mexicanas (ISR, IVA). Error común de empresas USA: tener empleados de ventas o técnicos en México que negocian y concierran contratos — eso típicamente constituye EP aunque no haya oficina formal. Fuente: CDI México-USA Art. 5; LISR Art. 2."),
r("¿Qué es el MAP (Mutual Agreement Procedure) y para qué sirve en el CDI México-USA?",
  "El MAP (Procedimiento de Mutuo Acuerdo) está establecido en el Art. 25 del CDI México-USA. Es el mecanismo para resolver conflictos cuando un contribuyente considera que la tributación aplicada por uno o ambos Estados no es conforme al convenio — principalmente en casos de doble tributación por ajustes de precios de transferencia. Cómo funciona: (1) El contribuyente presenta una solicitud MAP ante la autoridad competente de su país de residencia dentro de los 3 años desde la primera notificación del ajuste. (2) Las autoridades competentes (SAT y IRS) negocian bilateralmente para resolver el conflicto. (3) Si no llegan a acuerdo en cierto plazo, puede activarse arbitraje. Beneficio clave: si el SAT ajusta un precio de transferencia en México, el contribuyente puede solicitar un ajuste correlativo en USA vía MAP para evitar pagar impuesto doble sobre la misma renta. Fuente: CDI México-USA Art. 25; OCDE MAP Guidelines."),
r("¿Las S. de R.L. de C.V. mexicanas reciben el mismo tratamiento que una LLC en USA para fines fiscales?",
  "No automáticamente, pero pueden elegirlo. Las S. de R.L. de C.V. son entidades check-the-box bajo la regulación del IRS — esto significa que para fines fiscales estadounidenses, la entidad puede ELEGIR cómo ser clasificada: como corporación (paga impuesto a nivel entidad en USA), como partnership (ingresos fluyen directamente a los socios), o como entidad disregarded (ignorada fiscalmente, se consolida con el dueño). La elección tiene implicaciones significativas en el CDI México-USA: si la S. de R.L. es tratada como partnership en USA pero como persona moral (entidad separada) en México, puede haber desalineaciones en el acceso a beneficios del convenio. Esta es un área técnica compleja que requiere planeación fiscal bilateral cuidadosa. Fuente: IRS Check-the-Box Regulations (Treas. Reg. §301.7701); CDI México-USA; LISR."),
r("¿Por qué Estados Unidos no firmó el MLI (Instrumento Multilateral BEPS) y qué consecuencias tiene para el CDI México-USA?",
  "Estados Unidos decidió no adherirse al MLI (Instrumento Multilateral de la OCDE/G20, Acción 15 BEPS) porque considera que sus tratados bilaterales ya contienen protecciones anti-abuso suficientes (principalmente las cláusulas LOB). Consecuencia directa para el CDI México-USA: el CDI no está cubierto por el MLI, por lo que las modificaciones automáticas que el MLI hace a otros tratados de México (para incluir cláusulas PPT - Principal Purpose Test, MAP mejorado, arbitraje obligatorio) NO aplican al CDI con USA. Implicación práctica: el CDI México-USA sigue regido por sus términos originales de 1992 con el Protocolo de 1994. Para actualizar el CDI con USA conforme a los estándares BEPS, México y USA deberían negociar un nuevo protocolo bilateral — lo cual no ha ocurrido a mayo 2026. Fuente: MLI OCDE; CDI México-USA; SAT; IRS Tax Treaties."),
r("¿Qué es una maquiladora IMMEX y qué riesgos fiscales tiene respecto a precios de transferencia?",
  "Una maquiladora IMMEX (Industria Manufacturera, Maquiladora y de Servicios de Exportación) es una empresa manufacturera en México que procesa materiales importados temporalmente y exporta el producto terminado, principalmente para matrices en USA. Beneficios: tasa preferencial de ISR, IVA e IEPS diferidos en importaciones temporales. Riesgos de precios de transferencia: (1) La maquiladora es la parte que realiza funciones de manufactura limitada, mientras la matriz USA tiene los intangibles y asume los riesgos — el precio de transferencia debe reflejar esto. (2) El SAT exige que las maquiladoras demuestren que sus márgenes son consistentes con el principio de plena competencia (safe harbor o APA). (3) Riesgo de EP: si la actividad de la maquiladora excede la manufactura por cuenta ajena y comienza a ejercer funciones de venta, puede constituir un EP de la matriz USA en México. (4) El SAT ha intensificado auditorías IMMEX en 2026. Fuente: LISR Arts. 179-185; Decreto IMMEX; CDI México-USA Art. 5."),
r("¿Qué obligaciones tiene un residente fiscal mexicano con activos en Estados Unidos?",
  "Un residente fiscal mexicano con activos en USA tiene obligaciones en ambos países: En México (SAT): declarar los ingresos generados por esos activos en su declaración anual de ISR (México grava a residentes por ingresos mundiales). Si tiene cuentas financieras en USA con más de cierto umbral, puede tener obligación de declaración de activos en el extranjero. En USA (IRS): dependiendo del tipo de activo y actividad, puede tener obligaciones de retención (withholding) sobre rentas de fuente USA (dividendos, intereses, regalías). Si es US person (ciudadano o residente fiscal USA además de México), tiene obligación de FBAR y FATCA. Si solo es residente fiscal mexicano sin ciudadanía USA, las obligaciones en USA se limitan a rentas de fuente USA sujetas a retención. El CDI México-USA determina qué país tiene derecho preferente de gravar cada tipo de renta. Fuente: CDI México-USA; LISR Art. 1; IRS Publication 519."),
r("¿Cómo afecta el FATCA IGA entre México y USA a los bancos mexicanos?",
  "El Acuerdo Intergubernamental (IGA) FATCA entre México y USA de 2014 convierte a los bancos mexicanos en reportantes de información sobre cuentas de US persons. Obligaciones concretas: (1) Los bancos mexicanos deben identificar entre sus clientes a US persons (ciudadanos USA, residentes fiscales USA, entidades controladas por US persons). (2) Deben reportar anualmente al SAT la información de esas cuentas: nombre, número de cuenta, saldo, rentas. (3) El SAT transmite automáticamente esa información al IRS bajo el IGA. (4) Los bancos mexicanos que no cumplan FATCA están sujetos a retención del 30% sobre pagos de fuente USA que reciban. Prácticamente todos los bancos mexicanos de importancia están registrados ante el IRS como FFIs (Foreign Financial Institutions) participantes. Fuente: FATCA IGA México-USA 2014; IRC §§1471-1474; SAT; IRS."),
]

# ── FILE 09: Transfer Pricing ─────────────────────────────────────────────────
batch_09 = [
r("¿Cuáles son los métodos de precios de transferencia aceptados por el SAT en México?",
  "El SAT acepta los cinco métodos de la OCDE, con preferencia por los métodos tradicionales cuando existen comparables suficientes: Métodos tradicionales: (1) CUP (Comparable Uncontrolled Price): compara el precio en transacciones controladas vs. no controladas — preferido para bienes tangibles, regalías y servicios estandarizados. (2) RPM (Resale Price Method): compara el margen bruto del revendedor — usado principalmente en distribución. (3) CP (Cost Plus): compara el margen sobre costos — usado en manufactura, ensamblaje y servicios. Métodos de utilidad transaccional: (4) TNMM (Transactional Net Margin Method): compara márgenes netos (ROI, margen operativo) — el más usado cuando no hay comparables de precios directos. (5) PS (Profit Split): divide las ganancias combinadas entre partes vinculadas — usado en operaciones muy integradas o con intangibles únicos. Fuente: LISR Arts. 179-185; OCDE TP Guidelines 2022; SAT."),
r("¿Cuál es el umbral de ingresos que obliga a presentar el Reporte País por País (CbC) en México?",
  "El umbral para presentar el Reporte País por País (CbC Report) en México es que el grupo multinacional tenga ingresos consolidados superiores a 750 millones de euros en el ejercicio fiscal inmediato anterior. Si la empresa mexicana es la entidad controladora del grupo (matriz), presenta el CbC directamente al SAT. Si la empresa mexicana es una subsidiaria, la matriz del grupo presenta el CbC en su jurisdicción de residencia, y ese reporte se intercambia automáticamente con México si existe acuerdo de intercambio. El plazo para presentar el CbC report es de 12 meses después del cierre del ejercicio fiscal del grupo. El CbC contiene: ingresos, utilidades antes de impuestos, impuestos pagados, capital, activos tangibles y número de empleados por jurisdicción. Fuente: LISR Art. 76-A; OCDE BEPS Acción 13; SAT."),
r("¿Cuándo debe estar disponible el estudio de precios de transferencia (local file) en México?",
  "El estudio de precios de transferencia (local file) debe estar elaborado y disponible al momento de presentar la Declaración Informativa de Precios de Transferencia (DIPI), que generalmente se presenta en marzo del año siguiente al ejercicio fiscal (para personas morales con cierre en diciembre). Esto significa que el estudio debe estar listo en la práctica antes de marzo. No existe una fecha de entrega específica al SAT para el local file en condiciones normales — se conserva en poder del contribuyente y se presenta al SAT solo cuando lo solicita en ejercicio de sus facultades de comprobación (auditoría). Sin embargo, no tenerlo disponible cuando el SAT lo solicita genera infracciones y puede resultar en negación de deducciones. Fuente: LISR Arts. 76 y 179-185; RMF 2026; Garrigues."),
r("¿Qué sucede si el SAT ajusta los precios de transferencia de una empresa mexicana con operaciones en USA?",
  "Paso 1: El SAT emite un crédito fiscal por el ISR omitido correspondiente al ajuste de precios de transferencia, más actualizaciones, recargos y multas (hasta 100% del ISR omitido en casos graves). Paso 2: Se genera un problema de doble tributación: el ingreso ajustado en México ya fue gravado en USA en la parte de la contraparte. Paso 3: El contribuyente puede solicitar un ajuste correlativo en USA: presenta una solicitud de MAP (Mutual Agreement Procedure) ante el SAT bajo el Art. 25 del CDI México-USA, dentro de los 3 años desde la primera notificación del ajuste. Paso 4: El SAT y el IRS negocian para eliminar la doble tributación. Paso 5: Si no hay acuerdo, puede activarse arbitraje según las disposiciones del CDI. El MAP no suspende el pago del crédito fiscal en México — se puede garantizar o pagar y luego recuperar si el MAP resulta favorable. Fuente: LISR Arts. 179-185; CDI México-USA Art. 25; OCDE MAP Guidelines."),
r("¿Qué es un APA (Advance Pricing Agreement) y cuándo conviene solicitarlo?",
  "Un APA (Acuerdo Anticipado de Precios) es un acuerdo entre el contribuyente y la(s) autoridad(es) fiscal(es) que establece de antemano la metodología de precios de transferencia que se aplicará a transacciones específicas durante un período determinado. Tipos: Unilateral (solo con el SAT), Bilateral (SAT + IRS para operaciones MX-USA), Multilateral (múltiples jurisdicciones). Conviene solicitarlo cuando: el contribuyente tiene transacciones intragrupo complejas o de alto valor que generan incertidumbre, hay intangibles únicos o difíciles de valorar, el grupo ha tenido ajustes de precios de transferencia en el pasado, o se quiere certeza fiscal para operaciones futuras significativas. Beneficios: certeza sobre el tratamiento fiscal, reducción significativa del riesgo de auditoría durante la vigencia, y bases para resolver conflictos con el IRS mediante APA bilateral. El proceso en México puede tomar 1-3 años. Fuente: LISR Art. 34-A; OCDE TP Guidelines; SAT APA."),
r("¿La thin capitalization (subcapitalización) es un riesgo de precios de transferencia en México?",
  "Sí. La thin capitalization ocurre cuando una empresa financia sus operaciones principalmente con deuda de partes vinculadas en lugar de capital propio, generando deducciones de intereses que erosionan la base fiscal. México tiene reglas específicas: el Art. 28 fracción XXVII LISR limita la deducibilidad de intereses pagados a partes vinculadas extranjeras cuando la deuda excede 3 veces el capital contable (ratio 3:1). Los intereses sobre el exceso no son deducibles. Adicionalmente, el SAT puede reclasificar deuda como capital si determina que el financiamiento no cumple con el principio de plena competencia — es decir, que una parte independiente no prestaría en esas condiciones. Riesgo BEPS: la Acción 4 de BEPS recomienda límites adicionales basados en el EBITDA del grupo. México ha incorporado parcialmente estas recomendaciones. Fuente: LISR Art. 28 fracción XXVII; OCDE BEPS Acción 4; SAT."),
r("¿Qué información debe contener el Archivo Maestro (Master File) de precios de transferencia?",
  "El Master File proporciona una visión panorámica del grupo multinacional al SAT y otras autoridades. Contenido requerido conforme a BEPS Acción 13 (implementado en México): (1) Estructura organizacional: organigrama del grupo y jurisdicciones donde operan las entidades. (2) Descripción del negocio global: principales mercados, cadena de suministro, operaciones por geografía. (3) Intangibles globales: lista de intangibles significativos, quién los posee legalmente, quién los desarrolla, cómo se compensan las entidades. (4) Actividades de financiamiento intercompañía: préstamos intragrupo, política de tesorería centralizada, cash pooling. (5) Posiciones fiscales globales: descripción de posiciones fiscales que puedan ser de interés para las autoridades. (6) Estados financieros consolidados del grupo. El Master File proporciona contexto para entender por qué el Local File de la entidad mexicana tiene los márgenes que reporta. Fuente: LISR Art. 76-A; OCDE BEPS Acción 13; RMF 2026."),
r("¿Cuál es el método de precios de transferencia más apropiado para una distribuidora mexicana que vende productos de su matriz en USA?",
  "Para una distribuidora que compra productos de su matriz y los revende en México, el método más apropiado típicamente es el RPM (Resale Price Method) o el TNMM (Transactional Net Margin Method). RPM: compara el margen bruto de la distribuidora mexicana contra distribuidoras independientes comparables — es el método preferido cuando hay datos de margen bruto disponibles. TNMM: compara el margen neto operativo (Berry Ratio, margen operativo sobre ventas) de la distribuidora contra empresas comparables — se usa cuando no hay datos de margen bruto suficientes o cuando la distribuidora realiza funciones adicionales (marketing, logística). Para seleccionar: analiza las funciones que realiza la distribuidora (¿solo distribuye o también hace marketing significativo?), los riesgos que asume (¿inventario, crédito?) y los activos que usa. Mayor funcionalidad = mayor margen esperado. La base de comparables más usada en México es Amadeus/Orbis de Bureau van Dijk. Fuente: LISR Arts. 179-185; OCDE TP Guidelines; Garrigues."),
r("¿Qué son los hard-to-value intangibles (HTVI) bajo el marco BEPS y por qué son riesgosos?",
  "Los HTVI (Hard-to-Value Intangibles, OCDE BEPS Acción 8-10) son intangibles únicos o difíciles de valorar en el momento de la transacción debido a su naturaleza (tecnología en desarrollo, activos únicos sin comparables). El riesgo: cuando una empresa transfiere un intangible a una parte vinculada en una jurisdicción de baja tributación a un precio bajo, y ese intangible resulta ser muy valioso años después, el SAT y el IRS pueden usar resultados ex post (los resultados reales posteriores) para demostrar que el precio inicial fue subvaluado. Las OCDE BEPS Acciones 8-10 establecen que la remuneración por intangibles debe reflejar dónde se crean realmente el valor y las funciones de desarrollo, mejora, mantenimiento, protección y explotación (DEMPE). Ejemplos de HTVI frecuentes en MX-USA: software propietario, marcas en desarrollo, fórmulas farmacéuticas, algoritmos de IA. Fuente: OCDE BEPS Acciones 8-10; LISR Art. 179; SAT."),
r("¿Cuánto puede multar el SAT por no tener documentación de precios de transferencia?",
  "Las multas por incumplimiento de obligaciones de precios de transferencia en México son múltiples y acumulables: Por no presentar la DIPI: multa por omisión de declaración informativa, cuyo monto varía según la magnitud de las operaciones no reportadas. Por no tener el estudio de precios de transferencia cuando el SAT lo solicita: multa por incumplimiento de obligaciones de documentación (Arts. 81-82 CFF), más el riesgo de negación de deducciones de gastos con partes vinculadas. Por ajustes al precio de transferencia: ISR omitido + actualizaciones por inflación + recargos (intereses moratorios) + multas por omisión de pago que pueden llegar hasta el 100% del ISR omitido en casos graves. Por proporcionar información falsa en la DIPI: multas adicionales por datos incorrectos. En 2026 el SAT ha intensificado auditorías de precios de transferencia usando bases de datos Amadeus/Orbis y machine learning para detectar márgenes anómalos. Fuente: LISR Arts. 179-185; Arts. 81-82 CFF; SAT Plan Maestro 2026."),
]

# ── FILE 10: Análisis de Riesgo ───────────────────────────────────────────────
batch_10 = [
r("¿Qué es el enfoque basado en riesgo (EBR) que usa el SAT para priorizar auditorías?",
  "El Enfoque Basado en Riesgo (EBR) es la metodología del SAT para asignar perfiles de riesgo a contribuyentes y priorizar sus recursos de fiscalización en los casos de mayor riesgo de evasión. El SAT usa ATLAS (Análisis, Trazabilidad y Localización de Sujetos) para: segmentar contribuyentes por industria, tamaño y comportamiento tributario histórico, cruzar múltiples fuentes de datos (CFDI, declaraciones, movimientos bancarios, DIOT, datos de importaciones/exportaciones, registros de propiedad inmobiliaria y vehicular), y aplicar algoritmos de machine learning para detectar anomalías y patrones de evasión. El resultado es una puntuación de riesgo por contribuyente que determina la probabilidad y profundidad de una auditoría. Contribuyentes con proveedores EFOS, gastos desproporcionados, o inconsistencias CFDI-banco son automáticamente escalados a riesgo alto. Fuente: SAT Plan Maestro de Fiscalización; Metodología ATLAS; Art. 42 CFF (facultades de comprobación)."),
r("¿Qué significa que el SAT detecte emisión de CFDIs en horarios atípicos como red flag?",
  "La emisión de CFDIs en horarios atípicos (madrugada, fines de semana, feriados) es un indicador de que la facturación puede ser automatizada o fraudulenta — no refleja una operación comercial real que ocurre en esos momentos. ATLAS detecta este patrón cruzando la hora del timbre del CFDI contra el perfil operativo del emisor. Una empresa de construcción que emite el 80% de sus facturas entre las 2am y 4am los domingos activa una alerta de alto riesgo. Esto suele ser indicativo de: generación masiva automatizada de facturas falsas, uso de sistemas de facturación para emitir CFDIs sin operación real de respaldo, o acceso no autorizado al sistema de facturación (fraude interno). El horario de emisión por sí solo no es evidencia suficiente, pero combinado con otros red flags (concentración de clientes, ausencia de activos) eleva significativamente el riesgo. Fuente: Metodología ATLAS SAT; Art. 69-B CFF."),
r("¿Cuáles son las señales de alerta (red flags) para detectar estructuración de pagos o smurfing?",
  "La estructuración de pagos (smurfing) divide transacciones para mantenerse bajo umbrales de reporte. ATLAS y la UIF detectan estos red flags: (1) Múltiples depósitos de efectivo en cantidades ligeramente inferiores a $100,000 MXN (equivalente a $7,500 USD) realizados el mismo día o en días consecutivos en la misma o diferentes sucursales. (2) Múltiples CFDIs a diferentes clientes por montos casi idénticos que no corresponden al perfil de precios de la empresa. (3) Pagos fraccionados al mismo beneficiario a través de diferentes cuentas bancarias. (4) Correlación entre el número de transacciones y la proximidad al umbral de reporte — patrones que sugieren diseño deliberado para evadir el reporte. (5) Aumento repentino en la frecuencia de transacciones sin cambio en el volumen de negocios. La estructuración es delito bajo Art. 400 Bis CPF y 31 USC §5324 (USA). Fuente: LFPIORPI; Art. 400 Bis CPF; 31 USC §5324 BSA."),
r("¿Qué red flags específicos usa el SAT para detectar uso de paraísos fiscales en esquemas de evasión?",
  "ATLAS monitorea red flags específicos de estructuras con paraísos fiscales: (1) Pagos recurrentes de regalías, servicios técnicos o intereses a entidades en jurisdicciones en lista gris o negra de la OCDE — importes superiores al estándar del sector son señal crítica. (2) Deuda intragrupo con entidades en paraísos fiscales que excede el capital social (thin capitalization, violación del Art. 28 fracción XXVII LISR). (3) Estructuras de holding con múltiples capas de entidades en Islas Caimán, Bermudas, Luxemburgo, Países Bajos sin justificación de negocio real. (4) Flujos bancarios hacia jurisdicciones no cooperantes detectados en los reportes de las instituciones financieras a la UIF. (5) Ausencia de sustancia económica en las entidades intermedias: sin empleados, sin oficinas, sin función real. Desde 2020, México exige 'sustancia económica' para la deducibilidad de pagos a entidades en regímenes fiscales preferentes. Fuente: LISR Art. 176 y 28 fracc. XXVII; LFPIORPI; OCDE BEPS; SAT."),
r("¿Cómo detecta ATLAS inconsistencias entre declaraciones de IVA e ISR?",
  "ATLAS cruza automáticamente múltiples declaraciones del mismo contribuyente para detectar inconsistencias: ISR vs. IVA: si los ingresos declarados en ISR son significativamente diferentes a la base de IVA trasladado, el SAT presume omisión de ingresos o gastos artificiales. CFDI emitidos vs. ingresos declarados: si el total de CFDIs emitidos en el año supera lo declarado en ISR, hay presunción de ingresos no declarados. CFDI recibidos vs. IVA acreditable: si el IVA acreditado es mayor al que corresponde a los CFDIs recibidos válidos, el SAT detecta acreditamiento indebido. DIOT vs. CFDI recibidos: la DIOT que reportas al SAT sobre pagos a proveedores se cruza contra los CFDIs que esos proveedores te emitieron — discrepancias indican facturas no declaradas o proveedores EFOS. Estas inconsistencias se identifican algorítmicamente en ATLAS y generan alertas que priorizan al contribuyente para auditoría. Fuente: SAT ATLAS; LISR; LIVA; Art. 42 CFF."),
r("¿Qué son las operaciones con criptoactivos que deben reportarse a la UIF en México?",
  "La regulación de criptoactivos en México está en la LFPIORPI y sus modificaciones. Las operaciones que generan obligación de reporte a la UIF son: (1) Operaciones en efectivo o criptoactivos por montos superiores a 210 UMAs (aproximadamente $23,700 MXN en 2026) deben reportarse como Operaciones en Efectivo (ROE). (2) Pagos de comisiones relacionadas con operaciones en criptoactivos superiores a 4 UMAs (aproximadamente $452 MXN) también generan reporte. (3) Las Instituciones de Tecnología Financiera (ITFs) reguladas por la Ley Fintech están obligadas a reportar operaciones inusuales con criptoactivos. Red flags específicos: depósitos de exchanges de criptomonedas no reportados en declaraciones fiscales, operaciones en plataformas no registradas ante la CNBV, y conversiones frecuentes de criptomonedas a efectivo sin justificación de negocio. Fuente: LFPIORPI; Ley Fintech; CNBV; UIF 2025-2026."),
r("¿Cuál es el patrón de evasión más común que detecta el SAT mediante análisis de razones financieras?",
  "El patrón más frecuente que ATLAS detecta vía razones financieras es el margen bruto anómalo: una empresa reporta márgenes significativamente inferiores al promedio de su sector durante múltiples ejercicios — lo que indica gastos artificialmente inflados (facturas falsas) para reducir la utilidad fiscal. Los análisis específicos que usa ATLAS: (1) Rotación de inventarios: disminución abrupta sin justificación puede indicar compras ficticias que inflaron el inventario sin existencia física. (2) Período promedio de pago: plazos inusualmente largos con proveedores nuevos — los EFOS típicamente no cobran porque la operación no existió. (3) Ratio IVA causado/IVA acreditable: si el IVA acreditado es sistemáticamente alto en relación al causado, hay indicios de uso de facturas falsas para acreditamiento indebido. (4) Utilidad fiscal negativa recurrente: empresas con pérdidas fiscales durante 3+ ejercicios consecutivos en sectores normalmente rentables son candidatas a auditoría. Fuente: ATLAS SAT; OCDE Análisis de Riesgo Fiscal; Metodología EBR."),
r("¿Qué es el due diligence de proveedores y cómo lo implementa una empresa de manera efectiva?",
  "El due diligence de proveedores es el proceso de verificación previa y continua de la idoneidad fiscal y legal de los proveedores antes y durante la relación comercial. Para ATLAS, una implementación efectiva incluye: Verificación previa al contrato: (1) Consultar las listas EFOS/EDOS del SAT para el RFC del proveedor. (2) Verificar la constancia de situación fiscal y opinión de cumplimiento positiva del SAT. (3) Confirmar que el proveedor existe físicamente en su domicilio fiscal. (4) Revisar que el RFC esté activo y el régimen fiscal sea compatible con los servicios ofrecidos. Monitoreo continuo: (5) Configurar alertas automáticas para detectar cambios en el estatus del proveedor en listas EFOS/EDOS (el SAT actualiza semanalmente). (6) Revisar trimestralmente la opinión de cumplimiento de proveedores clave. Documentación: (7) Guardar evidencia del due diligence realizado en el expediente de cada proveedor por 5 años. Fuente: Art. 69-B CFF; LFPIORPI; LISR Art. 27; ValidaCFDI 2026."),
r("¿Qué significa que una empresa tenga un ratio de facturación por empleado 'excesivamente alto' para el SAT?",
  "El ratio de facturación por empleado (ingresos totales / número de empleados registrados en IMSS) es uno de los indicadores más potentes que usa ATLAS para detectar EFOS. Una empresa legítima tiene un límite físico de producción determinado por su personal: una despacho de abogados con 5 abogados difícilmente puede facturar $50M mensuales. Cuando ATLAS detecta que el ratio de una empresa supera significativamente el promedio de su sector, presume que la empresa no tiene la capacidad operativa para generar esa facturación — indicativo de empresa fantasma o EFOS. El SAT también cruza la facturación contra: número de empleados en IMSS, activos fijos declarados, energía eléctrica consumida (en algunos casos), y capacidad instalada del sector. Una empresa de manufactura con 3 empleados y $10M en facturación mensual activa alertas críticas. La corrección: si el ratio alto es legítimo (empresa muy tecnificada), documenta la automatización y tecnología usada. Fuente: Art. 69-B CFF; Metodología ATLAS; SAT Plan Maestro."),
r("¿Cómo puede ATLAS detectar activos no declarados de un contribuyente?",
  "ATLAS cruza múltiples registros públicos y privados para identificar activos que no corresponden a los ingresos declarados: (1) Registros de propiedad inmobiliaria: el SAT obtiene información del Registro Público de la Propiedad para cruzar inmuebles registrados a nombre del contribuyente contra su patrimonio declarado. (2) Registros vehiculares: vehículos de lujo registrados ante la SCT y tenencia federal identifican discrepancias con ingresos declarados. (3) Movimientos bancarios: las instituciones financieras reportan a la CNBV y UIF cuentas y movimientos significativos — ATLAS los cruza contra declaraciones. (4) Operaciones inmobiliarias: notarios tienen obligación de reportar compraventas a la UIF; el SAT cruza estas operaciones con los ingresos declarados. (5) Información de terceros: facturación recibida por el contribuyente reportada por sus proveedores en sus propios CFDIs. Si el patrimonio acumulado supera los ingresos netos declarados históricamente, el SAT presume ingresos no declarados e inicia procedimiento de discrepancia fiscal (Art. 91 LISR). Fuente: Art. 91 LISR; LFPIORPI; Metodología ATLAS."),
]

# ── Reporte General (11) ──────────────────────────────────────────────────────
batch_11 = [
r("¿Qué es el 'compliance program' que recomienda ATLAS para empresas con operaciones MX-USA?",
  "Un compliance program efectivo para operaciones MX-USA integra: (1) KYC (Know Your Customer/Counterparty) de proveedores: verificación inicial y monitoreo continuo de RFC contra listas EFOS/EDOS, opinión de cumplimiento SAT, y due diligence de materialidad. (2) Programa AML/CFT: políticas y procedimientos para prevenir lavado de dinero conforme a LFPIORPI en México y BSA en USA, incluyendo capacitación al personal, oficial de cumplimiento designado, y reportes a UIF/FinCEN. (3) Controles internos COSO: segregación de funciones, three-way match para pagos, límites de autorización por nivel jerárquico. (4) Monitoreo fiscal continuo: alertas de cambios en estatus de proveedores, validación de CFDIs antes de pago, revisión mensual de variaciones significativas. (5) Documentación de precios de transferencia: local file y DIPI al día para operaciones intragrupo. (6) Capacitación periódica al equipo directivo y operativo. Fuente: LFPIORPI; BSA; OCDE; COSO; Art. 69-B CFF."),
r("¿Cuáles son los principales cambios fiscales en México para 2026 que impactan a empresas con operaciones en USA?",
  "Los principales cambios para 2026 que impactan operaciones MX-USA: (1) Reforma CFDI 4.0 reforzada: nuevas validaciones de materialidad en tiempo real y Art. 49 Bis CFF para procedimientos abreviados de revisión de facturas irregulares. (2) RESICO expansión de causales de restricción de CSD bajo Art. 17-H Bis. (3) Intensificación de auditorías de precios de transferencia: el SAT usa Amadeus/Orbis y machine learning para detectar márgenes anómalos en 2026. (4) FinCEN NPRM abril 2026: propuesta de regulación que refuerza el risk-based approach en programas AML de instituciones financieras en USA, con énfasis en National Priorities y risk assessments. (5) Criptoactivos: mayor regulación y obligaciones de reporte a la UIF en México. (6) Sustancia económica: el SAT intensifica revisión de pagos a entidades en regímenes fiscales preferentes sin sustancia real. Fuente: CFF 2026; RMF 2026; FinCEN NPRM 2026; SAT Plan Maestro."),
r("¿Qué obligaciones fiscales tiene en México un ciudadano estadounidense que vive y trabaja en México?",
  "Un ciudadano estadounidense que establece residencia fiscal en México tiene obligaciones en AMBOS países. En México (SAT): si cumple los criterios de residencia fiscal (más de 183 días en el año o centro de intereses vitales en México), debe declarar ingresos mundiales en México y pagar ISR conforme a la LISR. Debe inscribirse en el RFC con su visa o condición migratoria correspondiente. En USA (IRS): USA grava a sus ciudadanos por ingresos mundiales independientemente de dónde vivan (citizenship-based taxation). Debe presentar declaración anual Form 1040 al IRS declarando todos sus ingresos, incluyendo los de México. FBAR (FinCEN Form 114): si tiene cuentas bancarias en México con saldo agregado >$10,000 en cualquier punto del año. Form 8938 (FATCA): si tiene activos financieros en México que superen los umbrales. El CDI México-USA ofrece crédito fiscal para evitar doble tributación — paga impuesto en México y usa ese pago como crédito contra el impuesto USA. Fuente: CDI México-USA; IRC §1 y §911; LISR Art. 9; IRS Publication 54."),
r("¿Qué es la discrepancia fiscal y cuándo la aplica el SAT?",
  "La discrepancia fiscal es el procedimiento del Art. 91 LISR mediante el cual el SAT puede presumir ingresos no declarados cuando detecta que las erogaciones (gastos, inversiones, depósitos, adquisiciones) de un contribuyente superan los ingresos declarados en el mismo período. El SAT activa este procedimiento cuando ATLAS detecta que el patrimonio o estilo de vida del contribuyente no corresponde a sus ingresos declarados. Fuentes de información que usa el SAT para detectar discrepancias: depósitos bancarios reportados por instituciones financieras, compraventas inmobiliarias reportadas por notarios, adquisición de vehículos de lujo, viajes internacionales, y en general cualquier gasto que deje huella en registros públicos o privados. Consecuencias: el SAT puede determinar un crédito fiscal sobre la discrepancia como ingresos omitidos, más multas y recargos. El contribuyente tiene derecho a demostrar que las erogaciones provienen de recursos ya gravados o exentos. Fuente: Art. 91 LISR; Metodología ATLAS SAT."),
r("¿Qué es el Reporte País por País (CbC) y qué información contiene?",
  "El Country-by-Country Report (CbCR) es un reporte de precios de transferencia introducido por BEPS Acción 13 que proporciona a las autoridades fiscales una visión de la distribución global de utilidades e impuestos de un grupo multinacional. Contenido: por cada jurisdicción donde opera el grupo: ingresos totales (de partes vinculadas y no vinculadas), utilidades/pérdidas antes de impuesto, impuesto sobre la renta pagado (efectivo), impuesto sobre la renta devengado (corriente), capital declarado, utilidades acumuladas, número de empleados, y activos tangibles distintos de efectivo. También incluye una lista de todas las entidades constituyentes del grupo con su jurisdicción fiscal y principales actividades. Por qué es poderoso: permite a las autoridades identificar si las utilidades se generan en jurisdicciones de alta tributación (donde están los empleados y activos) o se acumulan en paraísos fiscales (donde solo hay tenedoras de papel). Umbral de aplicación en México: grupos con ingresos consolidados >750 millones de euros. Fuente: LISR Art. 76-A; OCDE BEPS Acción 13; SAT."),
]

all_records = batch_05 + batch_06 + batch_07 + batch_08 + batch_09 + batch_10 + batch_11

with open(OUT, "a", encoding="utf-8") as f:
    for record in all_records:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")

print(f"Appended {len(all_records)} records (files 05-11)")
counts = {
    "05_CFDI": len(batch_05), "06_RESICO": len(batch_06),
    "07_NIF": len(batch_07), "08_MultiJuris": len(batch_08),
    "09_TransferPricing": len(batch_09), "10_Riesgo": len(batch_10),
    "11_General": len(batch_11),
}
for k, v in counts.items():
    print(f"  {k}: {v}")
